- name: Configuration du Load Balancer avec NGINX
  hosts: webservers
  become: true
  roles:
    - webserver

- name: Configuration du Load Balancer avec NGINX
  hosts: loadbalancer
  become: true
  roles:
    - loadbalancer

- name: Configuration du serveur DNS avec Bind9
  hosts: dns
  become: true
  roles:
    - dns
